usage: "&b&lFreeze &7| Invalid usage, try: /freeze <Player|Permission|All> <Player|Permission> <time>"
frozen: "&b&lFreeze &7| You have been frozen."
unFrozen: "&b&lFreeze &7| You have been unfrozen"
invalidPlayer: "&b&lFreeze &7| Invalid player"
unFreezeUsage: "&b&lFreeze &7| You have been unfrozen."
reload: "&b&lFreeze &7| Config has been reloaded."
lockdownOn: "&b&lFreeze &7| Lockdown has been enabled"
lockdownOff: "&b&lFreeze &7| Lockdown has been disabled"

lockdownOnTitle: "&7Server has went into lockdown"
lockdownOnSubTitle: "&7Please be patient"
lockdownOnTitleTime: 40
lockdownOnSound: ENTITY_VILLAGER_TRADE

lockdownOffTitle: "&7Lockdown mode disabled"
lockdownOffSubTitle: "&7You may now move again"
lockdownOffTitleTime: 40
lockdownOffSound: ENTITY_VILLAGER_TRADE


exempt:
  - permission.1
  - permission.2

freezeSound: ENTITY_VILLAGER_TRADE
freezeTitle: "&7You have been frozen!"
freezeTitleSubText: "&7Contact administration if you believe this is an issue"
freezeTitleTime: 40

unFreezeSound: ENTITY_VILLAGER_TRADE
unFreezeTitle: "&7You have been unfrozen!"
unFreezeSubTitle: "&7You may now move again."
unFreezeTitleTime: 40

example.permission:
  freezeTitle: "Example permission title"
  freezeSubTitle: "Example permission subtitle"
  freezeMessage: "Example message"
  freezeSound: ENTITY_VILLAGER_TRADE
  freezeTitleTime: 40
  unFreezeTitle: "Example permission title"
  unFreezeSubTitle: "Example permission subtitle"
  unFreezeMessage: "Example message"
  unFreezeSound: ENTITY_VILLAGER_TRADE
  unFreezeTitleTime: 40
